// Auto-generated gallery data. Dimensions baked in for layout stability.
export type GalleryImage = { src: string; w: number; h: number; alt: string };
export type GalleryCollection = { title: string; description: string; images: GalleryImage[] };

export const collections: GalleryCollection[] = [
  {
    title: "Weddings & Receptions",
    description: "Elegant spreads and seamless service for celebrations of every size.",
    images: [
      { src: "/images/gallery/gallery_21.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_22.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_23.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_24.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_25.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_26.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_27.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_28.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_29.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_30.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_31.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_32.jpg", w: 960, h: 720, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_59.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_60.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_61.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_62.jpg", w: 532, h: 800, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_63.jpg", w: 532, h: 800, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_64.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_65.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_66.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_67.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_68.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_69.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
      { src: "/images/gallery/gallery_70.jpg", w: 800, h: 532, alt: "Wedding reception catering by Afritouch" },
    ],
  },
  {
    title: "Corporate & Institutional",
    description: "Daily staff meals, breakfasts and refreshments for offices and institutions.",
    images: [
      { src: "/images/gallery/gallery_01.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_02.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_03.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_04.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_05.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_06.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_07.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_08.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_09.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_10.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_11.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_12.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_13.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_14.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_15.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
      { src: "/images/gallery/gallery_16.jpg", w: 1080, h: 1080, alt: "Corporate and institutional catering" },
    ],
  },
  {
    title: "Outdoor & Marquee Events",
    description: "On-site buffet lines and full service wherever your event takes place.",
    images: [
      { src: "/images/gallery/gallery_17.jpg", w: 2881, h: 1441, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_18.jpg", w: 1000, h: 973, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_19.jpg", w: 800, h: 1016, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_20.jpg", w: 1024, h: 677, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_45.jpg", w: 960, h: 640, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_46.jpg", w: 960, h: 640, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_47.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_48.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_49.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_50.jpg", w: 638, h: 960, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_51.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_52.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_53.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_54.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_55.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_56.jpg", w: 638, h: 960, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_57.jpg", w: 960, h: 638, alt: "Outdoor marquee event catering" },
      { src: "/images/gallery/gallery_58.jpg", w: 960, h: 720, alt: "Outdoor marquee event catering" },
    ],
  },
  {
    title: "Buffets & Presentation",
    description: "Plated dishes and abundant buffet spreads that put the food first.",
    images: [
      { src: "/images/gallery/gallery_33.jpg", w: 305, h: 322, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_34.jpg", w: 200, h: 200, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_35.jpg", w: 1080, h: 1080, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_36.jpg", w: 1080, h: 1080, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_37.jpg", w: 1080, h: 1080, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_38.jpg", w: 1080, h: 1080, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_39.jpg", w: 2048, h: 1361, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_40.jpg", w: 1361, h: 2048, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_41.jpg", w: 1361, h: 2048, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_42.jpg", w: 1361, h: 2048, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_43.jpg", w: 2048, h: 1536, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_44.jpg", w: 638, h: 960, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_71.jpg", w: 1080, h: 1080, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_72.jpg", w: 1080, h: 1080, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_73.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_74.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_75.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_76.jpg", w: 972, h: 972, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_77.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_78.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_79.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_80.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_81.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
      { src: "/images/gallery/gallery_82.jpg", w: 1000, h: 1000, alt: "Buffet spread and plated dishes" },
    ],
  },
];

export const allImages: GalleryImage[] = collections.flatMap((c) => c.images);
